services:
  backend:
    image: emraud119/flask-backend:latest
    ports:
      - "5000:5000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      TAVILY_API_KEY: ${TAVILY_API_KEY:-}
      DATABASE_UR: sqlite:///Travel.db  # Dockerfile에서 복사된 경로에 맞게 설정

  frontend:
    image: emraud119/react-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    